<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RuntimeIdentifiers>win-x64;linux-x64;linux-arm64</RuntimeIdentifiers>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <PublishAot>true</PublishAot>
        <PublishTrimmed>true</PublishTrimmed>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Suruga.Common\Suruga.Common.csproj" />
      <ProjectReference Include="..\Suruga.FFmpeg\Suruga.FFmpeg.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="System.Numerics.Tensors" Version="11.0.0-rc.1.26425.128" />
    </ItemGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugSymbols>false</DebugSymbols>
        <DebugType>None</DebugType>
    </PropertyGroup>
</Project>
