using System.Runtime.InteropServices;
using Suruga.FFmpeg.Primitives;

namespace Suruga.FFmpeg.Native;

[StructLayout(LayoutKind.Sequential)]
public unsafe struct AVCodecContext
{
    private nint av_class;
    private int log_level_offset;
    private AVMediaType codec_type;
    private AVCodec* codec;
    private int codec_id;
    private uint codec_tag;
    private void* priv_data;
    private nint @internal;
    private void* opaque;
    private long bit_rate;
    private int flags;
    private int flags2;
    private byte* extradata;
    private int extradata_size;
    private AVRational time_base;
    public AVRational pkt_timebase;
    private AVRational framerate;
    private int delay;
    private int width;
    private int height;
    private int coded_width;
    private int coded_height;
    private AVRational sample_aspect_ratio;
    private int pix_fmt;
    private int sw_pix_fmt;
    private int color_primaries;
    private int color_trc;
    private int colorspace;
    private int color_range;
    private int chroma_sample_location;
    private int field_order;
    private int refs;
    private int has_b_frames;
    private int slice_flags;
    private delegate* unmanaged[Cdecl]<AVCodecContext*, AVFrame*, int*, int, int, int, void> draw_horiz_band;
    private delegate* unmanaged[Cdecl]<AVCodecContext*, int*, int> get_format;
    private int max_b_frames;
    private float b_quant_factor;
    private float b_quant_offset;
    private float i_quant_factor;
    private float i_quant_offset;
    private float lumi_masking;
    private float temporal_cplx_masking;
    private float spatial_cplx_masking;
    private float p_masking;
    private float dark_masking;
    private int nsse_weight;
    private int me_cmp;
    private int me_sub_cmp;
    private int mb_cmp;
    private int lidct_cmp;
    private int dia_size;
    private int last_predictor_count;
    private int me_pre_cmp;
    private int pre_dia_size;
    private int me_subpel_quality;
    private int me_range;
    private int mb_decision;
    private ushort* intra_matrix;
    private ushort* inter_matrix;
    private ushort* chroma_intra_matrix;
    private int intra_dc_precision;
    private int mb_lmin;
    private int mb_lmax;
    private int bidir_refine;
    private int keyint_min;
    private int gop_size;
    private int mv0_threshold;
    private int slices;
    public int sample_rate;
    public AVSampleFormat sample_fmt;
    public AVChannelLayout ch_layout;
    private int frame_size;
    private int block_align;
    private int cutoff;
    private int audio_service_type;
    private int request_sample_fmt;
    private int initial_padding;
    private int trailing_padding;
    private int seek_preroll;
    private delegate* unmanaged[Cdecl]<AVCodecContext*, AVFrame*, int, int> get_buffer2;
    private int bit_rate_tolerance;
    private int global_quality;
    private int compression_level;
    private float qcompress;
    private float qblur;
    private int qmin;
    private int qmax;
    private int max_qdiff;
    private int rc_buffer_size;
    private int rc_override_count;
    private nint rc_override;
    private long rc_max_rate;
    private long rc_min_rate;
    private float rc_max_available_vbv_use;
    private float rc_min_vbv_overflow_use;
    private int rc_initial_buffer_occupancy;
    private int trellis;
    private byte* stats_out;
    private byte* stats_in;
    private int workaround_bugs;
    private int strict_std_compliance;
    private int error_concealment;
    private int debug;
    private int err_recognition;
    private nint hwaccel;
    private void* hwaccel_context;
    private nint hw_frames_ctx;
    private nint hw_device_ctx;
    private int hwaccel_flags;
    private int extra_hw_frames;
    private fixed ulong error[8];
    private int dct_algo;
    private int idct_algo;
    private int bits_per_coded_sample;
    private int bits_per_raw_sample;
    private int thread_count;
    private int thread_type;
    private int active_thread_type;
    private delegate* unmanaged[Cdecl]<AVCodecContext*, delegate* unmanaged<AVCodecContext*, void*, int>, void*, int*, int, int, int> execute;
    private delegate* unmanaged[Cdecl]<AVCodecContext*, delegate* unmanaged<AVCodecContext*, void*, int, int, int>, void*, int*, int, int> execute2;
    private int profile;
    private int level;
    private uint properties;
    private int skip_loop_filter;
    private int skip_idct;
    private int skip_frame;
    private int skip_alpha;
    private int skip_top;
    private int skip_bottom;
    private int lowres;
    private nint codec_descriptor;
    private byte* sub_charenc;
    private int sub_charenc_mode;
    private int subtitle_header_size;
    private byte* subtitle_header;
    private byte* dump_separator;
    private byte* codec_whitelist;
    private nint coded_side_data;
    private int nb_coded_side_data;
    private int export_side_data;
    private long max_pixels;
    private int apply_cropping;
    private int discard_damaged_percentage;
    private long max_samples;
    private delegate* unmanaged[Cdecl]<AVCodecContext*, AVPacket*, int, int> get_encode_buffer;
    private long frame_num;
    private int* side_data_prefer_packet;
    private uint nb_side_data_prefer_packet;
    private nint decoded_side_data;
    private int nb_decoded_side_data;
    private int alpha_mode;
}
