using System.Runtime.InteropServices;

namespace Suruga.FFmpeg.Native;

[StructLayout(LayoutKind.Sequential)]
public unsafe struct AVFormatContext
{
    private nint av_class;
    private AVInputFormat* iformat;
    private AVInputFormat* oformat;
    private void* priv_data;
    public AVIOContext* pb;
    private int ctx_flags;
    private uint nb_streams;
    public AVStream** streams;
    private uint nb_stream_groups;
    private nint stream_groups;
    private uint nb_chapters;
    private nint chapters;
    private char* url;
    private long start_time;
    public long duration;
    private long bit_rate;
    private uint packet_size;
    private int max_delay;
    public int flags;
    private long probesize;
    private long max_analyze_duration;
    private byte* key;
    private int keylen;
    private uint nb_programs;
    private nint programs;
    private int video_codec_id;
    private int audio_codec_id;
    private int subtitle_codec_id;
    private int data_codec_id;
    public AVDictionary* metadata;
    private long start_time_realtime;
    private int fps_probe_size;
    private int error_recognition;
    private AVIOInterruptCB interrupt_callback;
    private int debug;
    private int max_streams;
    private uint max_index_size;
    private uint max_picture_buffer;
    private long max_interleave_delta;
    private int max_ts_probe;
    private int max_chunk_duration;
    private int max_chunk_size;
    private int max_probe_packets;
    private int strict_std_compliance;
    private int event_flags;
    private int avoid_negative_ts;
    private int audio_preload;
    private int use_wallclock_as_timestamps;
    private int skip_estimate_duration_from_pts;
    private int avio_flags;
    private int duration_estimation_method;
    private long skip_initial_bytes;
    private uint correct_ts_overflow;
    private int seek2any;
    private int flush_packets;
    private int probe_score;
    private int format_probesize;
    private byte* codec_whitelist;
    private byte* format_whitelist;
    private byte* protocol_whitelist;
    private byte* protocol_blacklist;
    private int io_repositioned;
    private AVCodec* video_codec;
    private AVCodec* audio_codec;
    private AVCodec* subtitle_codec;
    private AVCodec* data_codec;
    private int metadata_header_padding;
    private void* opaque;
    private delegate* unmanaged[Cdecl]<AVFormatContext*, int, void*, nuint, int> av_format_control_message;
    private long output_ts_offset;
    private byte* dump_separator;
    private delegate* unmanaged[Cdecl]<AVFormatContext*, ref AVIOContext*, byte*, int, ref AVDictionary*, int> io_open;
    private delegate* unmanaged[Cdecl]<AVFormatContext*, AVIOContext*, int> io_close2;
    private long duration_probesize;
    private byte* name;
}
